"use strict";

const fs = require("node:fs");
const path = require("node:path");
const zlib = require("node:zlib");
const { promisify } = require("node:util");

const gzip = promisify(zlib.gzip);

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function writeJson(filePath, data) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

async function writeJsonLinesGzip(filePath, rows) {
  ensureDir(path.dirname(filePath));
  const jsonl = rows.map((row) => JSON.stringify(row)).join("\n");
  const compressed = await gzip(Buffer.from(`${jsonl}\n`, "utf8"));
  fs.writeFileSync(filePath, compressed);
}

function escapeLuaString(value) {
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")
    .replace(/"/g, "\\\"");
}

function toLua(value, indent = 0) {
  const spacing = "  ".repeat(indent);
  const childSpacing = "  ".repeat(indent + 1);

  if (value == null) {
    return "nil";
  }

  if (typeof value === "string") {
    return `"${escapeLuaString(value)}"`;
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "{}";
    }
    const items = value.map((entry) => `${childSpacing}${toLua(entry, indent + 1)}`);
    return `{\n${items.join(",\n")}\n${spacing}}`;
  }

  const entries = Object.entries(value);
  if (entries.length === 0) {
    return "{}";
  }

  const fields = entries.map(([key, fieldValue]) => {
    const isIdentifier = /^[A-Za-z_][A-Za-z0-9_]*$/.test(key);
    const renderedKey = isIdentifier ? key : `["${escapeLuaString(key)}"]`;
    return `${childSpacing}${renderedKey} = ${toLua(fieldValue, indent + 1)}`;
  });

  return `{\n${fields.join(",\n")}\n${spacing}}`;
}

function writeLuaModule(filePath, payload) {
  ensureDir(path.dirname(filePath));
  const content = [
    "-- Generated by the mplus-matrix pipeline.",
    `return ${toLua(payload)}`,
    "",
  ].join("\n");
  fs.writeFileSync(filePath, content, "utf8");
}

function formatIsoTimestamp(input = new Date()) {
  return new Date(input).toISOString();
}

function createLogger(verbose = false) {
  return {
    info(message) {
      process.stdout.write(`${message}\n`);
    },
    debug(message) {
      if (verbose) {
        process.stdout.write(`[debug] ${message}\n`);
      }
    },
    warn(message) {
      process.stderr.write(`[warn] ${message}\n`);
    },
  };
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

module.exports = {
  createLogger,
  ensureDir,
  formatIsoTimestamp,
  sleep,
  toLua,
  writeJson,
  writeJsonLinesGzip,
  writeLuaModule,
};
